### ISSUE TITLE
App Crash - Cannot append sample buffer: 

### ISSUE THREAD

**Issue by AndreaNocito** [OlegAba/LivePhotoGenerator#16]
I am getting this error randomly, usually after 4/5 successful tries:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVAssetWriterInput appendSampleBuffer:] Cannot append sample buffer: First input buffer must have an appropriate kCMSampleBufferAttachmentKey_TrimDurationAtStart since the codec has encoder delay'

The problems seems to be here:

`
    // Converts the video into a Live Photo format
    private static func convertVideoToLivePhotoFormat(inputVideoPath: String, outputVideoURL: URL, assetID: String, completion: @escaping (Bool, LPError?) -> ()) { 
    ...
                    if var buffer = output.copyNextSampleBuffer() {
                            if  !videoWriterInput.append(buffer) {
    ..
    `

**Comment by OlegAba** [comment]
I am no longer maintaining this project. I recommend using [LimitPoint/LivePhoto](https://github.com/LimitPoint/LivePhoto) instead. Thank you.
